### ISSUE TITLE
Feature Request: Alternate time inputs

### ISSUE THREAD

**Issue by codymikol** [nvzone/timerly#11]
When entering a time into timely I'd like it to interpret three different formats

`30` == `30 Minutes`
`1:30` == `1 Minute 30 Seconds`
`:30` == `30 seconds`

I don't mind doing the legwork on this, just wanted to get a greenlight before working on a PR

Nice project you've made. Volt is an interesting framework. :smile:

**Comment by siduck** [comment]
i'll try to add it today

**Comment by siduck** [comment]
hmm but its rare that users would just add seconds :thinking:
