### ISSUE TITLE
Errors when I try to set more than 59:59

### ISSUE THREAD

**Issue by KnightChaser** [nvzone/timerly#9]
When I accidentally set the time more than 59:59, I found that the `timerly` plugin crashes like below. It looks like there might be some exception checks. (I think the below picture is showing 1:09:00, but due to the original size of `timerly` plugin and some missing handling logics, I see runtime errors.)

![image](https://github.com/user-attachments/assets/6368d2da-4b6b-4ee7-846d-1bfb1963fa2f)

But overall, I like this plugin and I thought it'd be powerful if I integrate this with `lualine` plugin, as shown on discussion page. Keep going!

**Comment by siduck** [comment]
the timer is supposed to be less than 1 hour
